"""
Message handlers for the Viral Shorts Bot.

Handles:
- Text messages containing YouTube URLs
- Document (file) uploads (MP4, etc.)
- Pending settings input (e.g. number of shorts)
- Any other incoming messages
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from telegram import Update
from telegram.ext import ContextTypes

from configuration.config import (
    UPLOADS_DIR,
    TELEGRAM_ALLOWED_UPDATES,
)
from database import users as users_db
from database import settings as settings_db
from database import jobs as jobs_db
from database import statistics as stats_db
from telegram_handlers.common import (
    main_menu_keyboard,
    send_main_menu,
    log_command,
)
from utilities.security import (
    rate_limiter,
    validate_youtube_url,
    validate_uploaded_video,
    sanitise_filename,
    sanitise_text,
)
from utilities.queue_manager import QueueJob, queue_manager

logger = logging.getLogger(__name__)


# ===========================================================================
# Text message handler (YouTube URLs + settings input)
# ===========================================================================

async def handle_text_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handle incoming text messages.

    - If the text contains a YouTube URL, start processing.
    - If the user has a pending setting (e.g. num_shorts), process the input.
    - Otherwise, show the main menu.
    """
    user = update.effective_user
    if not user:
        return

    # Rate limit check
    if rate_limiter.is_rate_limited(user.id):
        remaining = rate_limiter.get_reset_seconds(user.id)
        await update.message.reply_text(
            f"⚠️ Rate limited. Try again in {remaining:.0f}s."
        )
        return

    # Ensure user exists in DB
    await users_db.upsert_user(
        user_id=user.id,
        username=user.username,
        first_name=user.first_name,
        last_name=user.last_name,
        language_code=user.language_code or "en",
    )

    text = update.message.text or ""
    text = sanitise_text(text)

    # Check for pending setting input
    pending_setting = context.user_data.get("pending_setting")
    if pending_setting:
        await _handle_pending_setting(update, context, user.id, pending_setting, text)
        return

    # Check for YouTube URL
    if _contains_youtube_url(text):
        await _handle_youtube_url(update, context, user.id, text)
        return

    # Default: show main menu
    await update.message.reply_text(
        "👋 Send me a *YouTube URL* or *upload a video* to create Shorts!\n\n"
        "Use the menu below for other options:",
        reply_markup=main_menu_keyboard(),
        parse_mode="Markdown",
    )


async def _contains_youtube_url(text: str) -> bool:
    """Check if the text contains a YouTube URL."""
    youtube_patterns = [
        "youtube.com/watch?v=",
        "youtu.be/",
        "youtube.com/shorts/",
        "youtube.com/live/",
        "youtube.com/playlist",
    ]
    text_lower = text.lower()
    return any(pattern in text_lower for pattern in youtube_patterns)


async def _handle_youtube_url(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    user_id: int,
    text: str,
) -> None:
    """Process a YouTube URL submission."""
    rate_limiter.register_request(user_id)

    # Validate URL
    is_valid, reason = validate_youtube_url(text)
    if not is_valid:
        await update.message.reply_text(f"❌ {reason}")
        return

    # Log the event
    await stats_db.log_event(
        event_type="video_downloaded",
        user_id=user_id,
        details={"url": text[:200], "source": "youtube"},
    )

    # Get user settings for the job
    settings = await settings_db.get_settings_for_job(user_id)

    # Acknowledge receipt
    status_msg = await update.message.reply_text(
        "📥 *Processing YouTube Video...*\n\n"
        "Downloading and analysing your video. "
        "This may take a few minutes.\n\n"
        "You'll receive updates as processing progresses.",
        parse_mode="Markdown",
    )

    # Create and submit job
    job = QueueJob(
        job_id="",  # Will be generated by create_job
        user_id=user_id,
        source_type="youtube",
        source_url=text,
        settings=settings,
    )

    # Create DB record first to get the job_id
    from database import jobs as jobs_db
    job_record = await jobs_db.create_job(
        user_id=user_id,
        source_type="youtube",
        source_url=text,
        num_shorts=settings.get("num_shorts", 3),
        settings_snapshot=settings,
    )
    job.job_id = job_record["job_id"]

    # Register progress callback
    async def on_progress(progress: int, message: str) -> None:
        try:
            await status_msg.edit_text(
                f"📥 *Processing...*\n\n"
                f"📊 Progress: {progress}%\n"
                f"📝 {message}",
                parse_mode="Markdown",
            )
        except Exception:
            pass  # Message may have been edited already

    queue_manager.register_progress_callback(job.job_id, on_progress)

    # Submit to queue
    # Override submit_job since we already created the DB record
    await queue_manager._queue.put(job)
    await stats_db.log_event(
        event_type="job_created",
        user_id=user_id,
        details={"job_id": job.job_id, "source_type": "youtube"},
    )

    logger.info("YouTube job %s submitted for user %d", job.job_id[:8], user_id)


# ===========================================================================
# Document / file upload handler
# ===========================================================================

async def handle_document_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handle document (file) uploads.

    Validates the file, downloads it, and submits a processing job.
    """
    user = update.effective_user
    if not user:
        return

    doc = update.message.document
    if not doc:
        return

    # Rate limit
    if rate_limiter.is_rate_limited(user.id):
        remaining = rate_limiter.get_reset_seconds(user.id)
        await update.message.reply_text(
            f"⚠️ Rate limited. Try again in {remaining:.0f}s."
        )
        return

    rate_limiter.register_request(user.id)

    # Validate
    is_valid, reason = validate_uploaded_video(update.message)
    if not is_valid:
        await update.message.reply_text(f"❌ {reason}")
        return

    # Ensure user exists
    await users_db.upsert_user(
        user_id=user.id,
        username=user.username,
        first_name=user.first_name,
        last_name=user.last_name,
        language_code=user.language_code or "en",
    )

    # Download file
    file_name = sanitise_filename(doc.file_name or "video.mp4")
    file_path = UPLOADS_DIR / f"{user.id}_{file_name}"

    status_msg = await update.message.reply_text(
        "📥 *Downloading your file...*\n\n"
        "This may take a moment depending on the file size.",
        parse_mode="Markdown",
    )

    try:
        file = await context.bot.get_file(doc.file_id)
        await file.download_to_drive(str(file_path))
    except Exception as e:
        logger.error("Failed to download file for user %d: %s", user.id, e)
        await status_msg.edit_text(f"❌ Failed to download file: {e}")
        return

    # Log upload event
    await stats_db.log_event(
        event_type="file_uploaded",
        user_id=user.id,
        details={"filename": file_name, "size": doc.file_size or 0},
    )

    # Get settings
    settings = await settings_db.get_settings_for_job(user.id)

    # Create job
    job_record = await jobs_db.create_job(
        user_id=user.id,
        source_type="upload",
        source_file_path=str(file_path),
        source_filename=file_name,
        num_shorts=settings.get("num_shorts", 3),
        settings_snapshot=settings,
    )

    # Update status
    await status_msg.edit_text(
        "📥 *File Received!*\n\n"
        f"*File:* `{file_name}`\n"
        f"*Size:* {(doc.file_size or 0) / (1024*1024):.1f} MB\n\n"
        "Processing will begin shortly. "
        "You'll receive updates as progress is made.",
        parse_mode="Markdown",
    )

    # Create job object and submit
    job = QueueJob(
        job_id=job_record["job_id"],
        user_id=user.id,
        source_type="upload",
        source_file_path=str(file_path),
        source_filename=file_name,
        settings=settings,
    )

    async def on_progress(progress: int, message: str) -> None:
        try:
            await status_msg.edit_text(
                f"📥 *Processing...*\n\n"
                f"📊 Progress: {progress}%\n"
                f"📝 {message}",
                parse_mode="Markdown",
            )
        except Exception:
            pass

    queue_manager.register_progress_callback(job.job_id, on_progress)
    await queue_manager._queue.put(job)

    logger.info("Upload job %s submitted for user %d", job.job_id[:8], user.id)


# ===========================================================================
# Video message handler (Telegram video files, not documents)
# ===========================================================================

async def handle_video_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handle video messages (sent as videos, not documents).

    These are also valid inputs for processing.
    """
    user = update.effective_user
    if not user:
        return

    video = update.message.video
    if not video:
        return

    # Rate limit
    if rate_limiter.is_rate_limited(user.id):
        remaining = rate_limiter.get_reset_seconds(user.id)
        await update.message.reply_text(
            f"⚠️ Rate limited. Try again in {remaining:.0f}s."
        )
        return

    rate_limiter.register_request(user.id)

    # For video messages, file_id is available
    file_name = f"video_{video.file_unique_id}.mp4"
    file_path = UPLOADS_DIR / f"{user.id}_{file_name}"

    status_msg = await update.message.reply_text(
        "📥 *Downloading your video...*",
        parse_mode="Markdown",
    )

    try:
        file = await context.bot.get_file(video.file_id)
        await file.download_to_drive(str(file_path))
    except Exception as e:
        logger.error("Failed to download video for user %d: %s", user.id, e)
        await status_msg.edit_text(f"❌ Failed to download video: {e}")
        return

    # Get settings
    settings = await settings_db.get_settings_for_job(user.id)

    # Create job
    job_record = await jobs_db.create_job(
        user_id=user.id,
        source_type="upload",
        source_file_path=str(file_path),
        source_filename=file_name,
        num_shorts=settings.get("num_shorts", 3),
        settings_snapshot=settings,
    )

    await status_msg.edit_text(
        f"✅ *Video Received!*\n\n"
        f"File: `{file_name}`\n"
        f"Duration: {video.duration}s\n\n"
        "Processing will begin shortly.",
        parse_mode="Markdown",
    )

    job = QueueJob(
        job_id=job_record["job_id"],
        user_id=user.id,
        source_type="upload",
        source_file_path=str(file_path),
        source_filename=file_name,
        settings=settings,
    )

    async def on_progress(progress: int, message: str) -> None:
        try:
            await status_msg.edit_text(
                f"📥 *Processing...*\n\n"
                f"📊 Progress: {progress}%\n"
                f"📝 {message}",
                parse_mode="Markdown",
            )
        except Exception:
            pass

    queue_manager.register_progress_callback(job.job_id, on_progress)
    await queue_manager._queue.put(job)

    logger.info("Video job %s submitted for user %d", job.job_id[:8], user.id)


# ===========================================================================
# Pending settings handler
# ===========================================================================

async def _handle_pending_setting(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    user_id: int,
    setting_key: str,
    text: str,
) -> None:
    """Handle input for a pending setting (e.g. number of shorts)."""
    if setting_key == "num_shorts":
        try:
            count = int(text)
            if not 1 <= count <= 20:
                raise ValueError("Out of range")
            await settings_db.update_num_shorts(user_id, count)
            await update.message.reply_text(
                f"✅ Number of Shorts set to *{count}*.",
                reply_markup=main_menu_keyboard(),
                parse_mode="Markdown",
            )
        except (ValueError, TypeError):
            await update.message.reply_text(
                "❌ Please enter a number between 1 and 20.",
                parse_mode="Markdown",
            )
            return

    # Clear pending setting
    context.user_data.pop("pending_setting", None)

    from telegram_handlers.common import log_setting_change
    await log_setting_change(user_id, setting_key, text)
